In [12]:
class Bill:
    def __init__(self,dic,Items):
        i = []
        for i,j in dic.items():
            print(i,j)
            acc = input(f"You Want {i} (Y/N)").upper()
            if acc == 'Y':
                 Items[i] = int(input(f"How Many {i} You Wnat : "))*j
        sum = 0
        for i,j in Items.items():
            sum = sum + j
        print(f"Total Amount to Pay{sum} ")
        print("1. Cash")
        print("2. Cheque")
        p_m = int(input("Enter Mehthod (1/2)"))
        if p_m == 1:
            print("Payment Method is Cash")
            d = {'500 Rs Notes:':500,'200 Rs Notes:':200,'100 Rs Notes:':100,'50 Rs Notes:':50}
            for i,j in d.items():
                if sum>=j:
                    print(f"{i}:,{sum 
// j}")
                    sum = sum%j
        else:
            print('Payment Method is Cheque')
            Chq_No = int(input("Enter Cheque Number:"))
            Bank = input("Enter Bank Name:")
            print()
            print("Cheque Details:")
            print("Cheque Number:",Chq_No)
            print("Bank Name:",Bank)
        

In [13]:
product = {'HHD':5000,'RAM':2000,'Printer':6000,'Pendrive':800}
p_items={'HHD':0,'RAM':0,'Printer':0,'Pendrive':0}
c=Bill(product,p_items)

HHD 5000
You Want HHD (Y/N)n
RAM 2000
You Want RAM (Y/N)n
Printer 6000
You Want Printer (Y/N)y
How Many Printer You Wnat : 2
Pendrive 800
You Want Pendrive (Y/N)y
How Many Pendrive You Wnat : 8
Total Amount to Pay18400 
1. Cash
2. Cheque
Enter Mehthod (1/2)1
Payment Method is Cash
500 Rs Notes::,36
200 Rs Notes::,2


In [7]:
for i in p_items:
    print(i)

HHD
RAM
Printer
Pendrive


In [16]:
import numpy as np
import sys

s = range(1000)
#print(s)
print("Size of each element of list in bites:",sys.getsizeof(s))
print("Size of whole list in bytes :",sys.getsizeof(s)*len(s))

d = np.arange(1000)
#print(d)
print("Size of each elemnt of numpy array in bytes: ",d.itemsize)
print('size of the whole numpy array in bytes: ',d.size*d.itemsize)

Size of each element of list in bites: 48
Size of whole list in bytes : 48000
Size of each elemnt of numpy array in bytes:  4
size of the whole numpy array in bytes:  4000


In [35]:
x = np.array([[[1,2,3,4,5,65,6,3,2,5]]])
print(x)
print(x[0,0,3])
print(x.ndim)

[[[ 1  2  3  4  5 65  6  3  2  5]]]
4
3


In [20]:
arr = np.array(42)
print(arr)
print(arr.ndim)

42
0


In [37]:
x = np.array([[1,2,3,4],[5,6,2,3]])
print(x)
print(x[0,3])
print(x.ndim)

[[1 2 3 4]
 [5 6 2 3]]
4
2


In [38]:
x = np.array([[1,2,3,4],[5,6,2,2,3]])
print(x)
print(x[0,3])
print(x.ndim)

[list([1, 2, 3, 4]) list([5, 6, 2, 2, 3])]


<ipython-input-38-d844d664ec8c>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  x = np.array([[1,2,3,4],[5,6,2,2,3]])


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [64]:
x = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
print(x)
print(x[0,-2,-2])
print(x.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
2
3


In [77]:
print(x[0:,0::2,::2])

[[[ 1  3]]

 [[ 7  9]]

 [[13 15]]]


In [100]:
x= np.array([1,2,3,4,5],ndmin=5)
print(x)
print(x.ndim)
print(x.shape)
n = x.reshape(1,5)
print(n)


[[[[[1 2 3 4 5]]]]]
5
(1, 1, 1, 1, 5)
[[1 2 3 4 5]]
[[[[1 2 3 4 5]]]]


In [114]:
a = np.array([[1,2],[3,4]])
for i in np.nditer(n):
    print(i)

1
2
3
4
5
