In [6]:
# Concatenate()
import numpy as np
arr1 = np.array([[[1,2,3],[2,3,4]]])
arr2 = np.array([[[4,5,6],[5,6,7]]])
arr3 = np.array([[[7,8,9],[8,9,10]]])
arr = np.concatenate((arr1,arr2,arr3))
print(arr)

[[[ 1  2  3]
  [ 2  3  4]]

 [[ 4  5  6]
  [ 5  6  7]]

 [[ 7  8  9]
  [ 8  9 10]]]


In [4]:
# Concatenate()
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.array([7,8,9])
arr = np.concatenate((arr1,arr2,arr3))
print(arr)

[1 2 3 4 5 6 7 8 9]


In [7]:
import numpy as np
arr1 = np.array([[1,2,3],[2,3,4]])
arr2 = np.array([[4,5,6],[5,6,7]])
arr3 = np.array([[7,8,9],[8,9,10]])
arr = np.concatenate((arr1,arr2,arr3),axis = 1)
print(arr)

[[ 1  2  3  4  5  6  7  8  9]
 [ 2  3  4  5  6  7  8  9 10]]


In [16]:
#array_split()
arr1 = np.array([1,2,3,4])
newarr=np.array_split(arr1,6)
print(newarr)

[array([1]), array([2]), array([3]), array([4]), array([], dtype=int32), array([], dtype=int32)]


In [23]:
arr1 = np.array([[1,2],[4,5],[6,7],[8,9]])
newarr = np.array_split(arr1,1,axis = 1)
print(newarr)

[array([[1, 2],
       [4, 5],
       [6, 7],
       [8, 9]])]


In [25]:
#where()
arr1=np.array([1,2,3,4,5,4,6,4,3])
x = np.where(arr1==4)
print(x)

(array([3, 5, 7], dtype=int64),)


In [26]:
arr1 = np.array([[1,2],[4,5],[4,7],[8,4]])
y = np.where(arr1==4)
print(y)

(array([1, 2, 3], dtype=int64), array([0, 0, 1], dtype=int64))


In [30]:
arr1 = np.array([[[1,2,3],[2,3,4]]])
arr2 = np.array([[[4,5,6],[5,4,7]]])
arr3 = np.array([[[7,8,9],[8,9,10]]])
arr = np.concatenate((arr1,arr2,arr3))
y = np.where(arr%2!=0)
print(y)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64), array([0, 0, 1, 0, 1, 1, 0, 0, 1], dtype=int64), array([0, 2, 1, 1, 0, 2, 0, 2, 1], dtype=int64))


In [39]:
#sort()
arr1=np.array([1,2,3,4,5,4,6,4,3])
x = np.sort(arr1)
print(x)

[1 2 3 3 4 4 4 5 6]


In [43]:
arr1=np.array(['banana','apple','cherry','abc'])
x = np.sort(arr1)
print(x)
arr2 = np.array([True,False,True])
print(np.sort(arr2,axis=0))

['abc' 'apple' 'banana' 'cherry']
[False  True  True]


In [58]:
arr1 = np.array([[5,2,4],[10,5,1],[4,7,8],[8,4,5]])
print(np.sort(arr1,axis=None))

[ 1  2  4  4  4  5  5  5  7  8  8 10]


In [68]:
arr = np.array([[[3,2,8],[7,9,3]],[[6,7,2],[9,6,4]]])
print(arr)
print('*'*100)
print(np.sort(arr,axis=0))
print('*'*100)
print(np.sort(arr,axis=1))
print('*'*100)
print(np.sort(arr,axis=2))

[[[3 2 8]
  [7 9 3]]

 [[6 7 2]
  [9 6 4]]]
****************************************************************************************************
[[[3 2 2]
  [7 6 3]]

 [[6 7 8]
  [9 9 4]]]
****************************************************************************************************
[[[3 2 3]
  [7 9 8]]

 [[6 6 2]
  [9 7 4]]]
****************************************************************************************************
[[[2 3 8]
  [3 7 9]]

 [[2 6 7]
  [4 6 9]]]


In [544]:
print(np.random.randint(1,7,size=(10)))

[3 1 3 1 3 6 5 3 3 2]


In [514]:
print(np.random.rand())

0.8672797672784306


In [529]:
print(np.random.choice(np.random.randint(1,7),size=(5)))

[0 0 0 0 0]


In [539]:
user = int(input("Gass the Number from (0,10)  : "))
count = 7
flage = 0
com = np.random.randint(0,11)
while count!=1:
    if user == com:
        print("Your Gass Is Right")
        print("You Win the Game")
        flage = 1
        break
    else:
        count -=1
        print(f"You Have {count} attempt Left")
        if com>user:
            print("your Gass Number is <")
        else:
            print("Your Gass Number is >")
        user = int(input("Gass the Number from (0,10)  : "))
if flage != 1:
    print("The Croect Number is : ",com)
    print("You Loss The Game")

Gass the Number from (0,10)  : 5
You Have 6 attempt Left
your Gass Number is <
Gass the Number from (0,10)  : 9
You Have 5 attempt Left
your Gass Number is <
Gass the Number from (0,10)  : 10
Your Gass Is Right
You Win the Game
